version: "3.7"

services:
  nginx:
    build: 
      context: ./docker/nginx
    volumes:
      - ./:/yiichat
    container_name: yiichat-nginx
    restart: always
    ports:
      - 80:80

  php-fpm:
    build: 
      context: ./docker/php-fpm
    volumes: 
      - ./:/yiichat
    container_name: yiichat-php-fpm
    depends_on: 
      - mysql

  php-cli:
    build:
      context: ./docker/php-cli
    volumes: 
      - ./:/yiichat
    command: sleep 100000
    container_name: yiichat-php-cli
  
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql
    ports:
      - 8183:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    depends_on: 
      - mysql